USE CH_App;
GO

-- 1. Bảng Người dùng
CREATE TABLE NguoiDung (
    MaNguoiDung INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(100),
    TaiKhoan VARCHAR(50) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL, 
    Email VARCHAR(100),
    VaiTro NVARCHAR(20) DEFAULT 'Member',
    SoDuVi DECIMAL(18, 2) DEFAULT 0
);

-- 2. Bảng Phòng
CREATE TABLE Phong (
    MaPhong INT PRIMARY KEY IDENTITY(1,1),
    TieuDe NVARCHAR(200),
    GiaThue DECIMAL(18, 2),
    MoTa NVARCHAR(MAX),
    TrangThai NVARCHAR(50) DEFAULT 'ChoDuyet',
    MaChuPhong INT FOREIGN KEY REFERENCES NguoiDung(MaNguoiDung)
);

-- 3. Bảng Ví ảo
CREATE TABLE ViAo (
    MaVi INT PRIMARY KEY IDENTITY(1,1),
    MaNguoiDung INT UNIQUE NOT NULL FOREIGN KEY REFERENCES NguoiDung(MaNguoiDung),
    SoDu DECIMAL(18, 2) DEFAULT 0,
    NgayCapNhat DATETIME DEFAULT GETDATE()
);